import AppKit

/// Single entry point for putting text at the user's cursor: pasteboard write + synthetic
/// Cmd+V + scheduled clipboard restore (gotchas 50, 52, 53). Everything touching
/// `NSPasteboard` and `CGEvent` stays on the main actor.
@MainActor
final class TextOutput: TextDelivering {
    typealias PasteAction = @MainActor () async -> Bool

    // Clipboard-manager etiquette types (Maccy, Raycast, Paste).
    static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Wait between the pasteboard write and Cmd+V so the pasteboard server has settled.
    static let prePasteDelay: Duration = .milliseconds(100)
    /// Slow (Electron) apps read the pasteboard late; never restore earlier than this.
    static let minimumRestoreDelay: Duration = .milliseconds(250)

    private let pasteboard: NSPasteboard
    private let pasteAction: PasteAction

    /// Restore scheduled by the last successful paste, cleared when it runs or is superseded.
    private var pendingRestore: PendingRestore?

    private struct PendingRestore {
        let snapshot: PasteboardSnapshot
        let changeCount: Int
        let task: Task<Void, Never>
    }

    /// `pasteAction` defaults to `KeySynth.pasteCommand()`; tests inject a fake outcome.
    init(pasteboard: NSPasteboard = .general, pasteAction: @escaping PasteAction = { await KeySynth.pasteCommand() }) {
        self.pasteboard = pasteboard
        self.pasteAction = pasteAction
    }

    // MARK: - TextDelivering

    func deliver(_ text: String, _ settings: OutputSettings) async -> OutputResult {
        let prepared = Self.prepare(text, trailingSpace: settings.trailingSpace)
        let signpostState = Log.signposter.beginInterval("paste")
        defer { Log.signposter.endInterval("paste", signpostState) }

        let snapshot = settings.restoreClipboard ? takeSnapshot() : nil
        cancelPendingRestore()

        write(prepared, transient: settings.restoreClipboard)
        let rememberedChangeCount = pasteboard.changeCount

        try? await Task.sleep(for: Self.prePasteDelay)
        let posted = await pasteAction()

        guard posted else {
            // Gotcha 53: no restore, the transcript stays as a normal copy.
            if settings.restoreClipboard {
                write(prepared, transient: false)
            }
            Log.output.warning("Paste failed, text left on the clipboard (\(prepared.count) chars)")
            return .copiedOnly(reason: String(localized: "Brak uprawnienia Dostępność"))
        }

        if let snapshot {
            scheduleRestore(snapshot, rememberedChangeCount: rememberedChangeCount, after: settings.restoreDelay)
        }
        Log.output.info("Pasted \(prepared.count) chars, restore \(snapshot == nil ? "off" : "scheduled", privacy: .public)")
        return .pasted
    }

    func copy(_ text: String) {
        cancelPendingRestore()
        write(text, transient: false)
    }

    /// Runs a scheduled clipboard restore now (app termination), with the same `changeCount` guard.
    func flushPendingRestore() {
        guard let pending = pendingRestore else { return }
        pending.task.cancel()
        pendingRestore = nil
        guard Self.shouldRestore(current: pasteboard.changeCount, remembered: pending.changeCount) else { return }
        pending.snapshot.restore(to: pasteboard)
        Log.output.info("Clipboard restored early on quit")
    }

    // MARK: - Helpers exposed for tests

    /// Trims whitespace and newlines, then appends one space when `trailingSpace` is on.
    static func prepare(_ text: String, trailingSpace: Bool) -> String {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        return trailingSpace ? trimmed + " " : trimmed
    }

    /// Restore only when nobody wrote to the pasteboard since our own write.
    static func shouldRestore(current: Int, remembered: Int) -> Bool {
        current == remembered
    }

    /// `restoreDelay` clamped to `minimumRestoreDelay`.
    static func effectiveRestoreDelay(_ delay: Duration) -> Duration {
        max(delay, minimumRestoreDelay)
    }

    // MARK: - Pasteboard

    /// Snapshot of the user's clipboard. When an earlier restore is still pending and the
    /// pasteboard still holds that paste's text, reuse its snapshot so two quick dictations
    /// do not "restore" our own transcript over the user's original clipboard.
    private func takeSnapshot() -> PasteboardSnapshot {
        if let pendingRestore, Self.shouldRestore(current: pasteboard.changeCount, remembered: pendingRestore.changeCount) {
            return pendingRestore.snapshot
        }
        return PasteboardSnapshot(capturing: pasteboard)
    }

    private func write(_ text: String, transient: Bool) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        pasteboard.setString(Bundle.main.bundleIdentifier ?? "com.captylo.app", forType: Self.sourceType)
        if transient {
            pasteboard.setData(Data(), forType: Self.transientType)
            pasteboard.setData(Data(), forType: Self.autoGeneratedType)
        }
    }

    private func scheduleRestore(_ snapshot: PasteboardSnapshot, rememberedChangeCount: Int, after delay: Duration) {
        let wait = Self.effectiveRestoreDelay(delay)
        let task = Task { @MainActor [weak self] in
            try? await Task.sleep(for: wait)
            guard !Task.isCancelled, let self else { return }
            defer { self.pendingRestore = nil }
            let current = self.pasteboard.changeCount
            guard Self.shouldRestore(current: current, remembered: rememberedChangeCount) else {
                Log.output.info("Clipboard restore skipped: changeCount moved \(rememberedChangeCount) -> \(current)")
                return
            }
            snapshot.restore(to: self.pasteboard)
            Log.output.debug("Clipboard restored (\(snapshot.items.count) item(s))")
        }
        pendingRestore = PendingRestore(snapshot: snapshot, changeCount: rememberedChangeCount, task: task)
    }

    private func cancelPendingRestore() {
        pendingRestore?.task.cancel()
        pendingRestore = nil
    }
}
